# Generated by Django 4.0.2 on 2022-02-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(blank=0, null=0, through='msiapp.DeviceAuthored', to='msiapp.Device'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='customer',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='device',
            order_with_respect_to=None,
        ),
    ]
