# Generated by Django 4.0.3 on 2022-03-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='my_user',
        ),
    ]
