# Generated by Django 4.0.2 on 2022-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0002_alter_customer_devices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='devices',
        ),
        migrations.AlterField(
            model_name='device',
            name='customers',
            field=models.ManyToManyField(blank=0, null=0, through='msiapp.DeviceAuthored', to='msiapp.Customer'),
        ),
    ]
