# Generated by Django 4.0.3 on 2022-03-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0002_rename_user_customer_my_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='my_user',
            new_name='user',
        ),
    ]
