# Generated by Django 4.0.2 on 2022-02-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0003_remove_customer_devices_alter_device_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='customers',
            field=models.ManyToManyField(through='msiapp.DeviceAuthored', to='msiapp.Customer'),
        ),
    ]
