# Generated by Django 4.0.2 on 2022-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msiapp', '0004_alter_device_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cus_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
